/**
 * Generates the animated SVG layer with native CSS @keyframes for the Hero scene.
 *
 * Visual Concept:
 *   Electromagnetic Field & Signal Geometry (inspired by Sagar's THz MIMO Antenna & DSP work).
 *   - Dual radiating antenna array elements (Element 01 & Element 02) generating phase interference
 *   - Calibrated polar / radiation pattern rays and azimuthal angle ticks (30°, 60°, 90°, etc.)
 *   - High-frequency traveling pulse packets along an electromagnetic transmission trace
 *   - Precision coordinate grid with telemetry readouts (frequency, phase, port status)
 *   - Oscilloscope scanning beam sweeping across the measurement field
 *   - Moiré interference fringe patterns generated by eccentric phase ellipses
 */

const W = 1200;
const H = 630;

function seeded(s: number) {
  return () => {
    s = (s * 16807 + 0) % 2147483647;
    return (s - 1) / 2147483646;
  };
}

export function generateAnimatedHeroLayer(): string {
  const p: string[] = [];

  // ── CSS Keyframe Styles ──────────────────────────────────────────
  p.push(`<style>
    /* Continuous slow phase rotation of antenna array radiation patterns */
    @keyframes rotateArrayA {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }
    @keyframes rotateArrayB {
      from { transform: rotate(360deg); }
      to { transform: rotate(0deg); }
    }

    /* Traveling high-frequency energy packets */
    @keyframes packetFlow {
      from { stroke-dashoffset: 400; }
      to { stroke-dashoffset: 0; }
    }
    @keyframes carrierFlow {
      from { stroke-dashoffset: 600; }
      to { stroke-dashoffset: 0; }
    }

    /* Oscilloscope / Field sweep line */
    @keyframes scanSweep {
      0% { transform: translateX(640px); opacity: 0; }
      4% { opacity: 0.35; }
      85% { opacity: 0.3; }
      100% { transform: translateX(1150px); opacity: 0; }
    }

    /* Telemetry indicator pulses */
    @keyframes portPulse {
      0%, 100% { opacity: 0.2; transform: scale(0.9); }
      50% { opacity: 0.95; transform: scale(1.15); }
    }
    @keyframes reticleTurn {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }

    /* Ambient coordinate shimmer */
    @keyframes coordTwinkleA {
      0%, 100% { opacity: 0.03; }
      50% { opacity: 0.16; }
    }
    @keyframes coordTwinkleB {
      0%, 100% { opacity: 0.14; }
      50% { opacity: 0.03; }
    }
    @keyframes fieldBreath {
      0%, 100% { opacity: 0.03; transform: scale(0.97); }
      50% { opacity: 0.065; transform: scale(1.03); }
    }

    .array-elem-a {
      transform-origin: 860px 190px;
      animation: rotateArrayA 72s linear infinite;
    }
    .array-elem-b {
      transform-origin: 970px 250px;
      animation: rotateArrayB 54s linear infinite;
    }
    .packet-trace {
      stroke-dasharray: 28 120;
      animation: packetFlow 5s linear infinite;
    }
    .carrier-trace {
      stroke-dasharray: 20 90;
      animation: carrierFlow 4s linear infinite;
    }
    .scanner-beam {
      animation: scanSweep 8s cubic-bezier(0.25, 0.1, 0.25, 1) infinite;
    }
    .port-diode {
      transform-origin: 860px 190px;
      animation: portPulse 2.8s ease-in-out infinite;
    }
    .reticle-slow {
      transform-origin: 860px 190px;
      animation: reticleTurn 30s linear infinite;
    }
    .shimmer-a {
      animation: coordTwinkleA 4.2s ease-in-out infinite;
    }
    .shimmer-b {
      animation: coordTwinkleB 3.6s ease-in-out infinite;
    }
    .ambient-field-glow {
      transform-origin: 915px 220px;
      animation: fieldBreath 9s ease-in-out infinite;
    }
  </style>`);

  p.push(`<g id="animated-hero-geometry">`);

  // ── 1. Coordinate Grid & Azimuthal Reference System ───────────────
  {
    const gx = 640, gy = 44, gw = 506, gh = 340, cell = 46;

    // Measurement sub-grid lines
    p.push(`<g opacity="0.9">`);
    for (let x = gx; x <= gx + gw; x += cell) {
      const isBorder = x === gx || x === gx + gw;
      const op = isBorder ? 0.05 : 0.018;
      p.push(`<line x1="${x}" y1="${gy}" x2="${x}" y2="${gy + gh}" stroke="rgba(255,255,255,${op})" stroke-width="${isBorder ? 0.6 : 0.3}"/>`);
    }
    for (let y = gy; y <= gy + gh; y += cell) {
      const isBorder = y === gy || y === gy + gh;
      const op = isBorder ? 0.05 : 0.018;
      p.push(`<line x1="${gx}" y1="${y}" x2="${gx + gw}" y2="${y}" stroke="rgba(255,255,255,${op})" stroke-width="${isBorder ? 0.6 : 0.3}"/>`);
    }
    p.push(`</g>`);

    // Polar radial lines projecting from Antenna Port 1 (860, 190)
    const angles = [0, 30, 45, 60, 75, 90, 120, 150, 210, 240, 270, 300, 330];
    for (const deg of angles) {
      const rad = (deg * Math.PI) / 180;
      const len = 320;
      const x2 = 860 + len * Math.cos(rad);
      const y2 = 190 + len * Math.sin(rad);
      // Clip line within reasonable viewport bounds
      if (x2 >= 500 && x2 <= 1180 && y2 >= 20 && y2 <= 610) {
        p.push(`<line x1="860" y1="190" x2="${x2.toFixed(1)}" y2="${y2.toFixed(1)}" stroke="rgba(255,255,255,0.025)" stroke-width="0.35" stroke-dasharray="2 6"/>`);
      }
    }

    // Concentric polar distance rings (range markers: r=70, 140, 210, 280)
    for (const r of [70, 140, 210, 280]) {
      p.push(`<circle cx="860" cy="190" r="${r}" fill="none" stroke="rgba(255,255,255,0.02)" stroke-width="0.35" stroke-dasharray="3 8"/>`);
    }

    // Telemetry crosshairs & annotations
    p.push(`<line x1="850" y1="190" x2="870" y2="190" stroke="rgba(255,255,255,0.15)" stroke-width="0.6"/>`);
    p.push(`<line x1="860" y1="180" x2="860" y2="200" stroke="rgba(255,255,255,0.15)" stroke-width="0.6"/>`);
    p.push(`<circle cx="860" cy="190" r="16" fill="none" stroke="rgba(255,255,255,0.06)" stroke-width="0.4" stroke-dasharray="2 3"/>`);

    p.push(`<line x1="962" y1="250" x2="978" y2="250" stroke="rgba(255,255,255,0.12)" stroke-width="0.5"/>`);
    p.push(`<line x1="970" y1="242" x2="970" y2="258" stroke="rgba(255,255,255,0.12)" stroke-width="0.5"/>`);

    // Factual engineering telemetry annotations
    p.push(`<text x="874" y="184" font-family="monospace" font-size="7" fill="rgba(255,255,255,0.10)" letter-spacing="1">PORT_01 // 1.0 THz</text>`);
    p.push(`<text x="982" y="246" font-family="monospace" font-size="7" fill="rgba(255,255,255,0.08)" letter-spacing="1">PORT_02 // Δφ = 45°</text>`);
    p.push(`<text x="650" y="58" font-family="monospace" font-size="7" fill="rgba(255,255,255,0.07)" letter-spacing="1.5">MIMO_SPATIAL_FIELD [2-ELEM]</text>`);

    // Traveling oscilloscope radar scan beam
    p.push(`<g class="scanner-beam">`);
    p.push(`<line x1="0" y1="${gy}" x2="0" y2="${gy + gh}" stroke="rgba(255,255,255,0.22)" stroke-width="0.75"/>`);
    p.push(`<rect x="-28" y="${gy}" width="28" height="${gh}" fill="url(#heroScanGrad)"/>`);
    p.push(`</g>`);
  }

  // ── 2. MIMO Dual-Array Electromagnetic Radiation Fringe Field ─────
  {
    // Element A: Radiation wave pattern (24 ellipses)
    p.push(`<g class="array-elem-a">`);
    for (let i = 0; i < 24; i++) {
      const r = 22 + i * 22;
      const rx = r;
      // Elliptical eccentricity derived from Bessel-like radial distribution
      const ry = r * (0.55 + 0.45 * Math.sin(i * 0.38 + 0.2));
      const t = i / 24;
      const op = Math.max(0.012, 0.125 * Math.exp(-Math.pow((t - 0.26) * 3, 2)));
      const rot = i * 3.4;
      p.push(
        `<ellipse cx="860" cy="190" rx="${rx.toFixed(1)}" ry="${ry.toFixed(1)}" ` +
        `fill="none" stroke="rgba(255,255,255,${op.toFixed(4)})" stroke-width="0.5" ` +
        `transform="rotate(${rot.toFixed(1)} 860 190)"/>`
      );
    }
    p.push(`</g>`);

    // Element B: Coupled radiating element (18 ellipses, counter-phase)
    p.push(`<g class="array-elem-b">`);
    for (let i = 0; i < 18; i++) {
      const r = 32 + i * 26;
      const rx = r;
      const ry = r * (0.60 + 0.40 * Math.sin(i * 0.42 + 0.3));
      const t = i / 18;
      const op = Math.max(0.012, 0.10 * Math.exp(-Math.pow((t - 0.3) * 3, 2)));
      const rot = 18 + i * 4.4;
      p.push(
        `<ellipse cx="970" cy="250" rx="${rx.toFixed(1)}" ry="${ry.toFixed(1)}" ` +
        `fill="none" stroke="rgba(255,255,255,${op.toFixed(4)})" stroke-width="0.45" ` +
        `transform="rotate(${rot.toFixed(1)} 970 250)"/>`
      );
    }
    p.push(`</g>`);

    // Rotating antenna reticle at Port 1
    p.push(`<g class="reticle-slow">`);
    p.push(`<circle cx="860" cy="190" r="28" fill="none" stroke="rgba(255,255,255,0.08)" stroke-width="0.5" stroke-dasharray="4 6"/>`);
    p.push(`<circle cx="860" cy="190" r="44" fill="none" stroke="rgba(255,255,255,0.04)" stroke-width="0.35" stroke-dasharray="2 9"/>`);
    p.push(`</g>`);

    // Blinking antenna port diode
    p.push(`<g class="port-diode">`);
    p.push(`<circle cx="860" cy="190" r="2.4" fill="#ffffff"/>`);
    p.push(`<circle cx="860" cy="190" r="6.5" fill="none" stroke="rgba(255,255,255,0.30)" stroke-width="0.5"/>`);
    p.push(`</g>`);
  }

  // ── 3. Signal Waveforms & Telemetry Traces ─────────────────────────
  {
    // Waveform A: Damped RF envelope crossing mid-canvas
    const pts1: string[] = [];
    for (let x = 40; x <= 720; x += 1.5) {
      const t = (x - 40) / 680;
      const amp = 52 * Math.exp(-t * 1.6) * Math.sin(t * Math.PI * 8);
      const y = 330 + amp;
      pts1.push(`${x.toFixed(1)},${y.toFixed(1)}`);
    }
    const poly1 = pts1.join(" ");
    p.push(`<polyline points="${poly1}" fill="none" stroke="rgba(255,255,255,0.035)" stroke-width="0.6"/>`);
    p.push(`<polyline points="${poly1}" fill="none" stroke="rgba(255,255,255,0.18)" stroke-width="0.85" class="packet-trace"/>`);

    // Waveform B: High-frequency carrier wave (lower region)
    const pts2: string[] = [];
    for (let x = 140; x <= 1120; x += 1.5) {
      const t = (x - 140) / 980;
      const freq = 3.5 + 11 * t;
      const envelope = Math.sin(t * Math.PI);
      const amp = 20 * envelope;
      const y = 496 + amp * Math.sin(t * Math.PI * freq);
      pts2.push(`${x.toFixed(1)},${y.toFixed(1)}`);
    }
    const poly2 = pts2.join(" ");
    p.push(`<polyline points="${poly2}" fill="none" stroke="rgba(255,255,255,0.025)" stroke-width="0.5"/>`);
    p.push(`<polyline points="${poly2}" fill="none" stroke="rgba(255,255,255,0.12)" stroke-width="0.7" class="carrier-trace"/>`);

    // Waveguide propagation arcs
    p.push(`<path d="M 40,140 C 200,110 460,195 860,188" fill="none" stroke="rgba(255,255,255,0.04)" stroke-width="0.5"/>`);
    p.push(`<path d="M 100,200 C 320,175 550,260 760,250" fill="none" stroke="rgba(255,255,255,0.025)" stroke-width="0.4"/>`);

    // Calibrated measurement baseline with scale ticks
    const x1 = 940, y1 = 54, x2 = 1150, y2 = 564;
    p.push(`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="rgba(255,255,255,0.03)" stroke-width="0.35"/>`);
    const dx = x2 - x1, dy = y2 - y1;
    const len = Math.sqrt(dx * dx + dy * dy);
    const nx = -dy / len, ny = dx / len;
    for (let i = 0; i <= 14; i++) {
      const t = i / 14;
      const px = x1 + dx * t;
      const py = y1 + dy * t;
      const tl = i % 5 === 0 ? 10 : 4;
      p.push(
        `<line x1="${(px - nx * tl).toFixed(1)}" y1="${(py - ny * tl).toFixed(1)}" ` +
        `x2="${(px + nx * tl).toFixed(1)}" y2="${(py + ny * tl).toFixed(1)}" ` +
        `stroke="rgba(255,255,255,0.04)" stroke-width="0.3"/>`
      );
    }
  }

  // ── 4. Precision Point Field / Shimmer Nodes ──────────────────────
  {
    const rand = seeded(55);
    p.push(`<g class="shimmer-a">`);
    for (let i = 0; i < 35; i++) {
      const x = 580 + rand() * 560;
      const y = 30 + rand() * 560;
      const dist = Math.sqrt((x - 860) ** 2 + (y - 190) ** 2);
      if (dist > 330) continue;
      const r = 0.4 + rand() * 0.9;
      p.push(`<circle cx="${x.toFixed(0)}" cy="${y.toFixed(0)}" r="${r.toFixed(1)}" fill="rgba(255,255,255,0.09)"/>`);
    }
    p.push(`</g>`);

    p.push(`<g class="shimmer-b">`);
    for (let i = 0; i < 35; i++) {
      const x = 580 + rand() * 560;
      const y = 30 + rand() * 560;
      const dist = Math.sqrt((x - 860) ** 2 + (y - 190) ** 2);
      if (dist > 330) continue;
      const r = 0.4 + rand() * 0.9;
      p.push(`<circle cx="${x.toFixed(0)}" cy="${y.toFixed(0)}" r="${r.toFixed(1)}" fill="rgba(255,255,255,0.06)"/>`);
    }
    p.push(`</g>`);
  }

  // ── 5. Technical Corner Brackets & Scribe Lines ───────────────────
  {
    for (const y of [20, 610]) {
      p.push(`<line x1="50" y1="${y}" x2="1150" y2="${y}" stroke="rgba(255,255,255,0.025)" stroke-width="0.3"/>`);
    }
    const bLen = 22;
    const bOff = 40;
    const corners = [
      { x: bOff, y: bOff, dx: 1, dy: 1 },
      { x: W - bOff, y: bOff, dx: -1, dy: 1 },
      { x: bOff, y: H - bOff, dx: 1, dy: -1 },
      { x: W - bOff, y: H - bOff, dx: -1, dy: -1 },
    ];
    for (const c of corners) {
      p.push(`<line x1="${c.x}" y1="${c.y}" x2="${c.x + c.dx * bLen}" y2="${c.y}" stroke="rgba(255,255,255,0.04)" stroke-width="0.4"/>`);
      p.push(`<line x1="${c.x}" y1="${c.y}" x2="${c.x}" y2="${c.y + c.dy * bLen}" stroke="rgba(255,255,255,0.04)" stroke-width="0.4"/>`);
    }
  }

  // ── 6. Gradients & Ambient Radiance ──────────────────────────────
  p.push(`<defs>
    <linearGradient id="heroScanGrad" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="white" stop-opacity="0"/>
      <stop offset="100%" stop-color="white" stop-opacity="0.08"/>
    </linearGradient>
    <radialGradient id="fieldRadiance" cx="915" cy="220" r="280" gradientUnits="userSpaceOnUse">
      <stop offset="0%" stop-color="white" stop-opacity="0.055"/>
      <stop offset="45%" stop-color="white" stop-opacity="0.012"/>
      <stop offset="100%" stop-color="white" stop-opacity="0"/>
    </radialGradient>
  </defs>`);

  p.push(`<circle cx="915" cy="220" r="280" fill="url(#fieldRadiance)" class="ambient-field-glow"/>`);

  p.push(`</g>`);
  return p.join("\n");
}
